/* Hand-authored search index. One entry per section (h2, and h3 where a
   page groups content under sub-sections). "page" is root-relative
   (no leading slash, no "../") - search.js resolves the right prefix
   at runtime based on where the current page lives. */
window.N2_SEARCH_INDEX = [
  { title: "N2 Docs", section: "Home", page: "index.html", excerpt: "Installation, configuration, commands, and exports for all four Native2 scripts.", keywords: "overview home n2-recoil n2-knockout n2-chat n2-laptop native2" },

  // n2-recoil
  { title: "Dependencies", section: "n2-recoil", page: "scripts/n2-recoil.html#dependencies", excerpt: "fx_version cerulean, game gta5, lua54. No hard dependency; auto-detects qbx_core / qb-core / es_extended for job multipliers.", keywords: "fx_version escrow_ignore qbx_core qb-core es_extended" },
  { title: "Installation", section: "n2-recoil", page: "scripts/n2-recoil.html#installation", excerpt: "Drop into resources/, ensure n2-recoil, edit config.lua.", keywords: "ensure server.cfg resources" },
  { title: "Configuration", section: "n2-recoil", page: "scripts/n2-recoil.html#configuration", excerpt: "Config.Enabled, Config.Multiplier, Config.AimMultiplier, Config.Chance, Config.Sway, Config.Jobs.", keywords: "Config.Enabled Config.Debug Config.Multiplier Config.AimMultiplier Config.Chance Config.MissMultiplier Config.Sway Config.SwayStrength Config.Jobs Config.Jobs.enabled Config.Jobs.onDutyOnly Config.Jobs.multipliers" },
  { title: "Recoil categories", section: "n2-recoil › Configuration", page: "scripts/n2-recoil.html#recoil-categories", excerpt: "Config.Categories, Config.Weapons, Config.Groups, Config.Overrides - per-weapon vertical/horizontal recoil tuning.", keywords: "Config.Categories Config.Weapons Config.Groups Config.Overrides pistol revolver smg rifle carbine shotgun lmg sniper marksman" },
  { title: "Commands", section: "n2-recoil", page: "scripts/n2-recoil.html#commands", excerpt: "No commands are registered by this script.", keywords: "none" },
  { title: "Exports / Events", section: "n2-recoil", page: "scripts/n2-recoil.html#exports-events", excerpt: "No exports. Listens for esx:setJob, QBCore:Client:OnJobUpdate, onResourceStop.", keywords: "esx:setJob esx:playerLoaded QBCore:Client:OnJobUpdate QBCore:Client:SetDuty onResourceStop" },
  { title: "Notes", section: "n2-recoil", page: "scripts/n2-recoil.html#notes", excerpt: "Ammo-delta detection, 70 degree camera pitch cap, framework fallback behavior.", keywords: "gotchas camera pitch cap DRUNK_SHAKE" },

  // n2-knockout
  { title: "Dependencies", section: "n2-knockout", page: "scripts/n2-knockout.html#dependencies", excerpt: "Requires ox_lib. Auto-detects qbx_core, qb-core, es_extended. Optional n2-chat integration.", keywords: "ox_lib qbx_core qb-core es_extended n2-chat" },
  { title: "Installation", section: "n2-knockout", page: "scripts/n2-knockout.html#installation", excerpt: "Install ox_lib first, ensure n2-knockout, edit config.lua.", keywords: "ox_lib ensure" },
  { title: "Configuration", section: "n2-knockout", page: "scripts/n2-knockout.html#configuration", excerpt: "Config.Debug, Config.Knockout, Config.Downed, Config.Effects, Config.Headache, Config.Sounds, Config.ChatIntegration.", keywords: "Config.Debug Config.MeleeWeapons Config.Knockout.HitsRequiredMin Config.Knockout.HitsRequiredMax Config.Screen Config.Downed.MaxTime Config.Downed.HealthRegenPerSec Config.Downed.SkillCheck Config.Effects.Blur Config.Effects.DrunkWalk Config.Effects.CameraSway Config.Effects.SlowMovement Config.Effects.ShootBlock Config.Effects.Trip Config.Effects.MuffledAudioScene Config.Headache Config.Sounds.Volume Config.Sounds.EarRinging Config.ChatIntegration" },
  { title: "Commands", section: "n2-knockout", page: "scripts/n2-knockout.html#commands", excerpt: "/n2_standup (client, bound to E) and /n2ko (server, debug-only self-knockout test).", keywords: "/n2_standup /n2ko standup keybind E test" },
  { title: "Exports / Events", section: "n2-knockout", page: "scripts/n2-knockout.html#exports-events", excerpt: "setKnockedOut, meleeHit, standUpAnnounce, standUp net events.", keywords: "n2-knockout:client:setKnockedOut n2-knockout:server:meleeHit standUpAnnounce standUp gameEventTriggered playerDropped" },
  { title: "NUI & locale", section: "n2-knockout", page: "scripts/n2-knockout.html#nui-locale", excerpt: "Transparent audio-only NUI page; locales/en.lua holds 5 notification strings.", keywords: "nui locale sounds playSound stopSound earring" },
  { title: "Notes", section: "n2-knockout", page: "scripts/n2-knockout.html#notes", excerpt: "Bridge load order, melee chip-damage healing, Config.Debug exposing /n2ko in production.", keywords: "gotchas bridge order qbx qbcore esx debug" },

  // n2-chat
  { title: "Dependencies", section: "n2-chat", page: "scripts/n2-chat.html#dependencies", excerpt: "Requires oxmysql. Optional ESX/QBCore/ox_core, emote resource, phone resource.", keywords: "oxmysql esx qbcore ox_core" },
  { title: "Installation", section: "n2-chat", page: "scripts/n2-chat.html#installation", excerpt: "Install oxmysql first, ensure n2-chat. n2_chat_scenes table auto-created.", keywords: "oxmysql ensure n2_chat_scenes" },
  { title: "general.lua", section: "n2-chat › Configuration", page: "scripts/n2-chat.html#general-lua", excerpt: "Config.Framework, Config.ChatKey, Config.Ranges, Config.FloodProtection, Config.AdminPermission, Config.Languages, Config.Emotes, Config.GrammarCorrection, Config.Commands.", keywords: "Config.Framework Config.ChatKey Config.FreeLookKey Config.ChatRange Config.Ranges Config.MaxMessages Config.FloodProtection Config.AdminPermission Config.Languages Config.Emotes Config.GrammarCorrection Config.Commands" },
  { title: "appearance.lua", section: "n2-chat › Configuration", page: "scripts/n2-chat.html#appearance-lua", excerpt: "Config.EnableFade, Config.Position, Config.Colors, Config.Timestamps, Config.TypingIndicator, Config.ActionBubble, Config.DistanceIntensity.", keywords: "Config.EnableFade Config.FadeTime Config.Position Config.Width Config.Height Config.FontSize Config.Colors Config.Timestamps Config.MenuAccentColor Config.TypingIndicator Config.ActionBubble Config.DistanceIntensity Config.ClientSettings" },
  { title: "moderation.lua", section: "n2-chat › Configuration", page: "scripts/n2-chat.html#moderation-lua", excerpt: "Config.WordFilter (censor/block), Config.DiscordWebhooks.", keywords: "Config.WordFilter censor block Config.DiscordWebhooks webhook chat reports moderation" },
  { title: "weapons.lua", section: "n2-chat › Configuration", page: "scripts/n2-chat.html#weapons-lua", excerpt: "Config.WeaponMe, Config.WeaponNames - weapon-draw auto /me.", keywords: "Config.WeaponMe Config.WeaponNames auto me" },
  { title: "phone.lua", section: "n2-chat › Configuration", page: "scripts/n2-chat.html#phone-lua", excerpt: "Config.PhoneCallRelay - enabled, script (lb-phone / qb-phone / qs-smartphone), types, prefix.", keywords: "Config.PhoneCallRelay lb-phone qb-phone qs-smartphone call relay" },
  { title: "scenes.lua", section: "n2-chat › Configuration", page: "scripts/n2-chat.html#scenes-lua", excerpt: "Config.SceneMarkers - maxTextLength, durations, radius, cooldowns.", keywords: "Config.SceneMarkers radius removeRadius markerType cooldown" },
  { title: "locale.lua", section: "n2-chat › Configuration", page: "scripts/n2-chat.html#locale-lua", excerpt: "Config.Locale strings; locale-de.lua ships but isn't wired in by default.", keywords: "locale-de german translation strings" },
  { title: "Commands", section: "n2-chat", page: "scripts/n2-chat.html#commands", excerpt: "/me /do /b /ooc /w /s /pm /cs /mute /report and 20+ more.", keywords: "/me /ame /amy /do /b /ooc /w /whisper /low /cw /s /shout /pm /r /reply /id /report /clear /chatsettings /lang /ag /cs /createscene /ds /deletescene /sa /sceneadmin /cash /info /mute /unmute /mutelist /clearchatall /a /ac /setnationality /announcement emotes" },
  { title: "Scene markers", section: "n2-chat", page: "scripts/n2-chat.html#scene-markers", excerpt: "Persistent world-placed RP notes via /cs, backed by n2_chat_scenes.", keywords: "/cs /createscene /ds /sa /sceneadmin n2_chat_scenes marker" },
  { title: "Phone call relay", section: "n2-chat", page: "scripts/n2-chat.html#phone-call-relay", excerpt: "Relays /say /shout /low into an active phone call. lb-phone / qb-phone / qs-smartphone support.", keywords: "lb-phone qb-phone qs-smartphone relay call" },
  { title: "Exports / Events", section: "n2-chat", page: "scripts/n2-chat.html#exports-events", excerpt: "SendMessage, Broadcast, RegisterCommand, GetDisplayName, SetMasked, chatMessage event.", keywords: "SendMessage SendSystemMessage Broadcast SendInRange RegisterCommand RegisterCommandMeta ClearChat GetChatHistory GetDisplayName SetMasked chatMessage" },
  { title: "Notes", section: "n2-chat", page: "scripts/n2-chat.html#notes", excerpt: "Load order requirement, word filter behavior, Discord webhook PM privacy.", keywords: "gotchas load order dependencies word filter webhook" },

  // n2-laptop
  { title: "Dependencies", section: "n2-laptop", page: "scripts/n2-laptop.html#dependencies", excerpt: "Requires ox_lib, ox_target, ox_inventory, oxmysql. Auto-detects qbx_core / qb-core / es_extended.", keywords: "ox_lib ox_target ox_inventory oxmysql qbx_core qb-core es_extended" },
  { title: "Installation & database", section: "n2-laptop", page: "scripts/n2-laptop.html#database", excerpt: "n2-laptop.sql, ox_inventory items (laptop, usb_stick, laptop_hack_device), Whispr/Market/Sell/Bank tables.", keywords: "n2-laptop.sql n2_whispr n2_market n2_sell n2_bank usb_stick usb_device laptop_hack_device install" },
  { title: "config/config.lua", section: "n2-laptop › Configuration", page: "scripts/n2-laptop.html#config-config-lua", excerpt: "Config.Laptop, Config.Shop, Config.Spotibeats, Config.Mail, Config.BrowserSites, Config.Market, Config.Sell, Config.Apps, Config.Extensions, Config.WhisprChannels.", keywords: "Config.Laptop Config.Shop Config.Spotibeats Config.Mail Config.BrowserSites Config.Market Config.Sell Config.Apps Config.Extensions Config.WhisprChannels openDistance autoLockMinutes usb hack difficulty" },
  { title: "config/marketplaces.lua", section: "n2-laptop › Configuration", page: "scripts/n2-laptop.html#config-marketplaces-lua", excerpt: "Config.Marketplaces - wishbay, haocang vendors and products.", keywords: "Config.Marketplaces wishbay haocang vendors products" },
  { title: "Bank (IonBank)", section: "n2-laptop › Apps", page: "scripts/n2-laptop.html#app-bank", excerpt: "Real bank balance plus a transaction ledger in n2_bank_transactions.", keywords: "ionbank ledger n2_bank_transactions balance" },
  { title: "Cryptex", section: "n2-laptop › Apps", page: "scripts/n2-laptop.html#app-cryptex", excerpt: "Fake cryptocurrency, server-wide price drift, 10% launder fee to bank.", keywords: "crypto CTX launder fee price drift" },
  { title: "Mail", section: "n2-laptop › Apps", page: "scripts/n2-laptop.html#app-mail", excerpt: "Scam email templates that genuinely charge the laptop's bank.", keywords: "scam phishing templates email" },
  { title: "Market (WishBay/HaoCang)", section: "n2-laptop › Apps", page: "scripts/n2-laptop.html#app-market", excerpt: "Server-validated checkout, shipping fee, pickup depot delivery.", keywords: "wishbay haocang shipping pickup depot order checkout" },
  { title: "Placement", section: "n2-laptop › Apps", page: "scripts/n2-laptop.html#app-placement", excerpt: "Ghost-prop placement flow, owner give-back on resource stop.", keywords: "ghost prop raycast place" },
  { title: "Sell (SellHub)", section: "n2-laptop › Apps", page: "scripts/n2-laptop.html#app-sell", excerpt: "NPC negotiation over Whispr, meetup, robbery chance, reputation.", keywords: "sellhub negotiation robbery reputation meetup" },
  { title: "USB", section: "n2-laptop › Apps", page: "scripts/n2-laptop.html#app-usb", excerpt: "Per-item file storage tied to the USB stick, not the laptop.", keywords: "usb file storage maxFiles" },
  { title: "Whispr", section: "n2-laptop › Apps", page: "scripts/n2-laptop.html#app-whispr", excerpt: "Private messaging scoped to the laptop item - DMs, groups, channels.", keywords: "whispr messaging DM groups channels" },
  { title: "Commands", section: "n2-laptop", page: "scripts/n2-laptop.html#commands", excerpt: "None - all interaction via ox_target and NUI.", keywords: "none ox_target" },
  { title: "Exports / Events", section: "n2-laptop", page: "scripts/n2-laptop.html#exports-events", excerpt: "n2-laptop.useLaptop, GetLaptopHistory, PostWhisprChannelMessage.", keywords: "useLaptop GetLaptopHistory PostWhisprChannelMessage" },
  { title: "Notes", section: "n2-laptop", page: "scripts/n2-laptop.html#notes", excerpt: "Laptop-scoped data, usb_stick/usb_device name mismatch, hardcoded currency rates.", keywords: "gotchas usb_stick usb_device mismatch currency rates cryptex" }
];
